const currenciesData = [
  { code: "AED", name: "united arab emirates dirham" },
  { code: "AFN", name: "afghan afghani" },
  { code: "ALL", name: "albanian lek" },
  { code: "AMD", name: "armenian dram" },
  { code: "ANG", name: "netherlands antillean guilder" },
  { code: "AOA", name: "angolan kwanza" },
  { code: "ARS", name: "argentine peso" },
  { code: "AUD", name: "australian dollar" },
  { code: "AWG", name: "aruban florin" },
  { code: "AZN", name: "azerbaijani manat" },
  { code: "BAM", name: "bosnia-herzegovina convertible mark" },
  { code: "BBD", name: "barbadian dollar" },
  { code: "BDT", name: "bangladeshi taka" },
  { code: "BGN", name: "bulgarian lev" },
  { code: "BHD", name: "bahraini dinar" },
  { code: "BIF", name: "burundian franc" },
  { code: "BMD", name: "bermudan dollar" },
  { code: "BND", name: "brunei dollar" },
  { code: "BOB", name: "bolivian boliviano" },
  { code: "BRL", name: "brazilian real" },
  { code: "BSD", name: "bahamian dollar" },
  { code: "BTC", name: "bitcoin" },
  { code: "BTN", name: "bhutanese ngultrum" },
  { code: "BWP", name: "botswanan pula" },
  { code: "BYN", name: "new belarusian ruble" },
  { code: "BYR", name: "belarusian ruble" },
  { code: "BZD", name: "belize dollar" },
  { code: "CAD", name: "canadian dollar" },
  { code: "CDF", name: "congolese franc" },
  { code: "CHF", name: "swiss franc" },
  { code: "CLF", name: "chilean unit of account (uf)" },
  { code: "CLP", name: "chilean peso" },
  { code: "CNY", name: "chinese yuan" },
  { code: "COP", name: "colombian peso" },
  { code: "CRC", name: "costa rican colón" },
  { code: "CUC", name: "cuban convertible peso" },
  { code: "CUP", name: "cuban peso" },
  { code: "CVE", name: "cape verdean escudo" },
  { code: "CZK", name: "czech republic koruna" },
  { code: "DJF", name: "djiboutian franc" },
  { code: "DKK", name: "danish krone" },
  { code: "DOP", name: "dominican peso" },
  { code: "DZD", name: "algerian dinar" },
  { code: "EGP", name: "egyptian pound" },
  { code: "ERN", name: "eritrean nakfa" },
  { code: "ETB", name: "ethiopian birr" },
  { code: "EUR", name: "euro" },
  { code: "FJD", name: "fijian dollar" },
  { code: "FKP", name: "falkland islands pound" },
  { code: "GBP", name: "british pound sterling" },
  { code: "GEL", name: "georgian lari" },
  { code: "GGP", name: "guernsey pound" },
  { code: "GHS", name: "ghanaian cedi" },
  { code: "GIP", name: "gibraltar pound" },
  { code: "GMD", name: "gambian dalasi" },
  { code: "GNF", name: "guinean franc" },
  { code: "GTQ", name: "guatemalan quetzal" },
  { code: "GYD", name: "guyanaese dollar" },
  { code: "HKD", name: "hong kong dollar" },
  { code: "HNL", name: "honduran lempira" },
  { code: "HRK", name: "croatian kuna" },
  { code: "HTG", name: "haitian gourde" },
  { code: "HUF", name: "hungarian forint" },
  { code: "IDR", name: "indonesian rupiah" },
  { code: "ILS", name: "israeli new sheqel" },
  { code: "IMP", name: "manx pound" },
  { code: "INR", name: "indian rupee" },
  { code: "IQD", name: "iraqi dinar" },
  { code: "IRR", name: "iranian rial" },
  { code: "ISK", name: "icelandic króna" },
  { code: "JEP", name: "jersey pound" },
  { code: "JMD", name: "jamaican dollar" },
  { code: "JOD", name: "jordanian dinar" },
  { code: "JPY", name: "japanese yen" },
  { code: "KES", name: "kenyan shilling" },
  { code: "KGS", name: "kyrgystani som" },
  { code: "KHR", name: "cambodian riel" },
  { code: "KMF", name: "comorian franc" },
  { code: "KPW", name: "north korean won" },
  { code: "KRW", name: "south korean won" },
  { code: "KWD", name: "kuwaiti dinar" },
  { code: "KYD", name: "cayman islands dollar" },
  { code: "KZT", name: "kazakhstani tenge" },
  { code: "LAK", name: "laotian kip" },
  { code: "LBP", name: "lebanese pound" },
  { code: "LKR", name: "sri lankan rupee" },
  { code: "LRD", name: "liberian dollar" },
  { code: "LSL", name: "lesotho loti" },
  { code: "LTL", name: "lithuanian litas" },
  { code: "LVL", name: "latvian lats" },
  { code: "LYD", name: "libyan dinar" },
  { code: "MAD", name: "moroccan dirham" },
  { code: "MDL", name: "moldovan leu" },
  { code: "MGA", name: "malagasy ariary" },
  { code: "MKD", name: "macedonian denar" },
  { code: "MMK", name: "myanma kyat" },
  { code: "MNT", name: "mongolian tugrik" },
  { code: "MOP", name: "macanese pataca" },
  { code: "MRO", name: "mauritanian ouguiya" },
  { code: "MUR", name: "mauritian rupee" },
  { code: "MVR", name: "maldivian rufiyaa" },
  { code: "MWK", name: "malawian kwacha" },
  { code: "MXN", name: "mexican peso" },
  { code: "MYR", name: "malaysian ringgit" },
  { code: "MZN", name: "mozambican metical" },
  { code: "NAD", name: "namibian dollar" },
  { code: "NGN", name: "nigerian naira" },
  { code: "NIO", name: "nicaraguan córdoba" },
  { code: "NOK", name: "norwegian krone" },
  { code: "NPR", name: "nepalese rupee" },
  { code: "NZD", name: "new zealand dollar" },
  { code: "OMR", name: "omani rial" },
  { code: "PAB", name: "panamanian balboa" },
  { code: "PEN", name: "peruvian nuevo sol" },
  { code: "PGK", name: "papua new guinean kina" },
  { code: "PHP", name: "philippine peso" },
  { code: "PKR", name: "pakistani rupee" },
  { code: "PLN", name: "polish zloty" },
  { code: "PYG", name: "paraguayan guarani" },
  { code: "QAR", name: "qatari rial" },
  { code: "RON", name: "romanian leu" },
  { code: "RSD", name: "serbian dinar" },
  { code: "RUB", name: "russian ruble" },
  { code: "RWF", name: "rwandan franc" },
  { code: "SAR", name: "saudi riyal" },
  { code: "SBD", name: "solomon islands dollar" },
  { code: "SCR", name: "seychellois rupee" },
  { code: "SDG", name: "sudanese pound" },
  { code: "SEK", name: "swedish krona" },
  { code: "SGD", name: "singapore dollar" },
  { code: "SHP", name: "saint helena pound" },
  { code: "SLL", name: "sierra leonean leone" },
  { code: "SOS", name: "somali shilling" },
  { code: "SRD", name: "surinamese dollar" },
  { code: "STD", name: "são tomé and príncipe dobra" },
  { code: "SVC", name: "salvadoran colón" },
  { code: "SYP", name: "syrian pound" },
  { code: "SZL", name: "swazi lilangeni" },
  { code: "THB", name: "thai baht" },
  { code: "TJS", name: "tajikistani somoni" },
  { code: "TMT", name: "turkmenistani manat" },
  { code: "TND", name: "tunisian dinar" },
  { code: "TOP", name: "tongan paʻanga" },
  { code: "TRY", name: "turkish lira" },
  { code: "TTD", name: "trinidad and tobago dollar" },
  { code: "TWD", name: "new taiwan dollar" },
  { code: "TZS", name: "tanzanian shilling" },
  { code: "UAH", name: "ukrainian hryvnia" },
  { code: "UGX", name: "ugandan shilling" },
  { code: "USD", name: "united states dollar" },
  { code: "UYU", name: "uruguayan peso" },
  { code: "UZS", name: "uzbekistan som" },
  { code: "VEF", name: "venezuelan bolívar fuerte" },
  { code: "VND", name: "vietnamese dong" },
  { code: "VUV", name: "vanuatu vatu" },
  { code: "WST", name: "samoan tala" },
  { code: "XAF", name: "cfa franc beac" },
  { code: "XAG", name: "silver (troy ounce)" },
  { code: "XAU", name: "gold (troy ounce)" },
  { code: "XCD", name: "east caribbean dollar" },
  { code: "XDR", name: "special drawing rights" },
  { code: "XOF", name: "cfa franc bceao" },
  { code: "XPF", name: "cfp franc" },
  { code: "YER", name: "yemeni rial" },
  { code: "ZAR", name: "south african rand" },
  { code: "ZMK", name: "zambian kwacha (pre-2013)" },
  { code: "ZMW", name: "zambian kwacha" },
  { code: "ZWL", name: "zimbabwean dollar" },
  { code: "Others", name: "Others" }
]
